spring:
    activemq:
        broker-url: tcp://ggnlabvm-mqoe02:61616
        user: admin
        password: admin
        pool:
            enabled: true
            max-connections: 50
    jpa:
        hibernate.ddl-auto: create
    datasource:
        url: jdbc:mysql://localhost:3306/ordermanagement
        username: root
        password: hsc321