spring:
    activemq:
        broker-url: tcp://ggnlabvm-mqoe02:61616
        user: admin
        password: admin
        pool:
            enabled: true
            max-connections: 50
           
    jpa:
        hibernate.ddl-auto: create
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    datasource:
        url: jdbc:mysql://192.168.251.64:3306/orderfullfillment
        username: root
        password: hsc321
        driver-class-name: com.mysql.jdbc.Driver
